# Site settings
title: Photon Impact
email: liujienju@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
description: a place to host random thoughts
baseurl: "/photon-impact" # the subpath of your site, e.g. /blog/
url: "http://passerby007.github.io" # the base hostname & protocol for your site
# twitter_username:
github_username:  passerby007

# Build settings
markdown: kramdown
